import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent


def test_models_match_generated_migrations():
    """Fails when a model changes without an autogenerated migration (see CLAUDE.md)."""
    r = subprocess.run(
        [sys.executable, "-m", "alembic", "check"],
        cwd=ROOT,
        env=os.environ,
        capture_output=True,
        text=True,
    )
    assert r.returncode == 0, r.stdout + r.stderr
