"""inquiry pipeline

Revision ID: 1d1e1c5680e2
Revises: 958fe6b45158
Create Date: 2026-09-29 10:33:21.869451

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d1e1c5680e2"
down_revision: str | Sequence[str] | None = "958fe6b45158"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inquiry_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("inquiry_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("note", "stage", "system", name="eventkind", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('note', 'stage', 'system')", name=op.f("ck_inquiry_events_kind_values")
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_inquiry_events_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["inquiry_id"],
            ["inquiries.id"],
            name=op.f("fk_inquiry_events_inquiry_id_inquiries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inquiry_events")),
    )
    op.create_index(
        op.f("ix_inquiry_events_inquiry_id"), "inquiry_events", ["inquiry_id"], unique=False
    )
    op.add_column(
        "inquiries",
        sa.Column(
            "stage",
            sa.Enum(
                "new",
                "contacted",
                "quoted",
                "won",
                "lost",
                name="stage_values",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="new",
            nullable=False,
        ),
    )
    op.add_column(
        "inquiries",
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("inquiries", sa.Column("read_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_column("inquiries", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inquiries", sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False)
    )
    op.drop_column("inquiries", "read_at")
    op.drop_column("inquiries", "archived")
    op.drop_column("inquiries", "stage")
    op.drop_index(op.f("ix_inquiry_events_inquiry_id"), table_name="inquiry_events")
    op.drop_table("inquiry_events")
    # ### end Alembic commands ###
