"""site image slots

Revision ID: 2c1b13aaaf05
Revises: 7995bda82c39
Create Date: 2026-09-29 11:45:56.449311

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c1b13aaaf05"
down_revision: str | Sequence[str] | None = "7995bda82c39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("site_settings", sa.Column("logo_asset_id", sa.Integer(), nullable=True))
    op.add_column("site_settings", sa.Column("tagline_asset_id", sa.Integer(), nullable=True))
    op.add_column("site_settings", sa.Column("og_asset_id", sa.Integer(), nullable=True))
    op.add_column("site_settings", sa.Column("favicon_asset_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_site_settings_tagline_asset_id_assets"),
        "site_settings",
        "assets",
        ["tagline_asset_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_site_settings_og_asset_id_assets"),
        "site_settings",
        "assets",
        ["og_asset_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_site_settings_favicon_asset_id_assets"),
        "site_settings",
        "assets",
        ["favicon_asset_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_site_settings_logo_asset_id_assets"),
        "site_settings",
        "assets",
        ["logo_asset_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_site_settings_logo_asset_id_assets"), "site_settings", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_site_settings_favicon_asset_id_assets"), "site_settings", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_site_settings_og_asset_id_assets"), "site_settings", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_site_settings_tagline_asset_id_assets"), "site_settings", type_="foreignkey"
    )
    op.drop_column("site_settings", "favicon_asset_id")
    op.drop_column("site_settings", "og_asset_id")
    op.drop_column("site_settings", "tagline_asset_id")
    op.drop_column("site_settings", "logo_asset_id")
    # ### end Alembic commands ###
