"""initial content tables

Revision ID: fe9c95707cb4
Revises:
Create Date: 2026-09-29 07:33:35.571643

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe9c95707cb4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legal_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("slug ~ '^[a-z0-9-]+$'", name=op.f("ck_legal_pages_slug_format")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_pages")),
        sa.UniqueConstraint("slug", name=op.f("uq_legal_pages_slug")),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("summary", sa.String(length=300), nullable=False),
        sa.Column("ios_url", sa.String(length=500), nullable=True),
        sa.Column("android_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "live", "coming_soon", "retired", name="projectstatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('live', 'coming_soon', 'retired')", name=op.f("ck_projects_status_values")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "site_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_email", sa.String(length=254), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("notify_email", sa.String(length=254), nullable=False),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("facebook_url", sa.String(length=500), nullable=True),
        sa.Column("instagram_url", sa.String(length=500), nullable=True),
        sa.Column("x_url", sa.String(length=500), nullable=True),
        sa.Column("tiktok_url", sa.String(length=500), nullable=True),
        sa.Column("youtube_url", sa.String(length=500), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_site_settings_single_row")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("site_settings")
    op.drop_table("projects")
    op.drop_table("legal_pages")
    # ### end Alembic commands ###
